/**
 * Session-local fallback registry for charts that are generated by module UI
 * but do not yet have a result-specific extractor. Manual extractors remain the
 * authoritative source for persisted analysis results; this registry closes
 * the gap for client-side and transient plots after they have been rendered.
 */
export interface RuntimePlotAsset {
  id: string
  module: string
  moduleLabel: string
  group: string
  label: string
  plotData: unknown[]
  plotLayout?: unknown
}

const assets = new Map<string, RuntimePlotAsset>()

const cleanKey = (value: string) => value.trim().replace(/\s+/g, ' ')

export function registerRuntimePlotAsset(asset: Omit<RuntimePlotAsset, 'id'> & { key?: string }) {
  const key = cleanKey(asset.key || `${asset.module}|${asset.group}|${asset.label}`)
  assets.set(key, {
    id: `runtime:${key}`,
    module: asset.module,
    moduleLabel: asset.moduleLabel,
    group: asset.group,
    label: asset.label,
    plotData: asset.plotData,
    plotLayout: asset.plotLayout,
  })
}

export function listRuntimePlotAssets(): RuntimePlotAsset[] {
  return [...assets.values()]
}

export function clearRuntimePlotAssets() {
  assets.clear()
}
