import type { BibliographyEntry } from './types'

/** Offline citation metadata. URLs are optional conveniences; the citation remains
 * readable when Perdura is offline. Controlled/proprietary works deliberately do
 * not point at local or redistributed copies. */
export const HELP_BIBLIOGRAPHY: BibliographyEntry[] = [
  {
    id: 'nist-eda-handbook',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/',
    note: 'Public primary reference for exploratory data analysis, probability models, testing, process control, experimental design, and reliability methods. Individual topics should add a section locator when possible.',
    publicAccess: true,
  },
  {
    id: 'nist-apr-censoring',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods, §8.1.3.1: Censoring',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/apr/section1/apr131.htm',
    note: 'Definitions and likelihood implications of right-, interval-, and multiply-censored reliability observations.',
    publicAccess: true,
  },
  {
    id: 'nist-alt-mle',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods, §8.4.2.2: Maximum Likelihood for Acceleration Models',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/apr/section4/apr422.htm',
    note: 'Joint likelihood estimation across stress cells, censored observations, model checks, and approximate confidence bounds.',
    publicAccess: true,
  },
  {
    id: 'nist-ks',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods, §1.3.5.16: Kolmogorov–Smirnov Goodness-of-Fit Test',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/eda/section3/eda35g.htm',
    note: 'ECDF-based statistic, critical-value conventions, and important limitations when parameters are estimated.',
    publicAccess: true,
  },
  {
    id: 'nist-proportion-ci',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods: Confidence Intervals for a Proportion',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/prc/section2/prc241.htm',
    note: 'Binomial-proportion interval construction and interpretation.',
    publicAccess: true,
  },
  {
    id: 'nist-process-stability',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods, §3.4.5: Assessing Process Stability',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/ppc/section4/ppc45.htm',
    note: 'Phase-I stability assessment before capability interpretation.',
    publicAccess: true,
  },
  {
    id: 'nist-spc',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods, §6.3: Univariate and Multivariate Control Charts',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/pmc/section3/pmc3.htm',
    note: 'Control-chart selection, construction, and interpretation.',
    publicAccess: true,
  },
  {
    id: 'nist-gage-rr',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods: Gauge Repeatability and Reproducibility Studies',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/mpc/section4/mpc4.htm',
    note: 'Measurement-process characterization, repeatability, reproducibility, and study design.',
    publicAccess: true,
  },
  {
    id: 'nist-variance-components',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods, §7.4.4: What Are Variance Components?',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/prc/section4/prc44.htm',
    note: 'ANOVA decomposition and estimation of sources of variation.',
    publicAccess: true,
  },
  {
    id: 'nist-response-surface',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods: Response Surface Designs',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/pri/section3/pri336.htm',
    note: 'Central-composite and related response-surface design principles.',
    publicAccess: true,
  },
  {
    id: 'nist-blocking',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods: Blocking a Design',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/pri/section3/pri332.htm',
    note: 'Using blocks to account for nuisance variation and associated confounding risks.',
    publicAccess: true,
  },
  {
    id: 'nist-degradation',
    author: 'NIST/SEMATECH',
    title: 'e-Handbook of Statistical Methods, §8.4.2.3: Fitting Models Using Degradation Data',
    year: '2012',
    url: 'https://www.itl.nist.gov/div898/handbook/apr/section4/apr423.htm',
    note: 'Degradation modeling as an alternative source of life and acceleration information.',
    publicAccess: true,
  },
  {
    id: 'turnbull-1976',
    author: 'B. W. Turnbull',
    title: 'The Empirical Distribution Function with Arbitrarily Grouped, Censored and Truncated Data',
    year: '1976',
    edition: 'Journal of the Royal Statistical Society, Series B, 38(3), 290–295',
    url: 'https://doi.org/10.1111/j.2517-6161.1976.tb01597.x',
    note: 'Foundational nonparametric treatment of interval-censored and grouped survival observations.',
    publicAccess: false,
  },
  {
    id: 'hurvich-tsai-1989',
    author: 'C. M. Hurvich and C.-L. Tsai',
    title: 'Regression and Time Series Model Selection in Small Samples',
    year: '1989',
    edition: 'Biometrika, 76(2), 297–307',
    url: 'https://doi.org/10.1093/biomet/76.2.297',
    note: 'Small-sample correction leading to AICc.',
    publicAccess: false,
  },
  {
    id: 'nelson-2003',
    author: 'Wayne B. Nelson',
    title: 'Recurrent Events Data Analysis for Product Repairs, Disease Recurrences, and Other Applications',
    year: '2003',
    edition: '1st ed., ASA–SIAM Series on Statistics and Applied Probability',
    url: 'https://doi.org/10.1137/1.9780898718454',
    note: 'Mean cumulative function and recurrent-event methods; use chapter/section locators supplied with individual citations.',
    publicAccess: false,
  },
  {
    id: 'lawless-nadeau-1995',
    author: 'J. F. Lawless and C. Nadeau',
    title: 'Some Simple Robust Methods for the Analysis of Recurrent Events',
    year: '1995',
    edition: 'Technometrics, 37(2), 158–168',
    url: 'https://doi.org/10.1080/00401706.1995.10484317',
    note: 'Robust variance estimation and comparison for recurrent-event mean functions.',
    publicAccess: false,
  },
  {
    id: 'meeker-escobar-1998',
    author: 'W. Q. Meeker and L. A. Escobar',
    title: 'Statistical Methods for Reliability Data',
    year: '1998',
    edition: 'Wiley Series in Probability and Statistics',
    url: 'https://doi.org/10.1002/9781118594486',
    note: 'Likelihood-based reliability analysis, competing risks, confidence intervals, and simulation-based inference.',
    publicAccess: false,
  },
  {
    id: 'kijima-1989',
    author: 'M. Kijima',
    title: 'Some Results for Repairable Systems with General Repair',
    year: '1989',
    edition: 'Journal of Applied Probability, 26(1), 89–102',
    url: 'https://doi.org/10.2307/3214319',
    note: 'Virtual-age models for imperfect repair, including the Type-II update used by Perdura.',
    publicAccess: false,
  },
  {
    id: 'mauchly-1940',
    author: 'J. W. Mauchly',
    title: 'Significance Test for Sphericity of a Normal n-Variate Distribution',
    year: '1940',
    edition: 'The Annals of Mathematical Statistics, 11(2), 204–209',
    url: 'https://doi.org/10.1214/aoms/1177731915',
    note: 'Classical test of the sphericity assumption in repeated-measures analysis.',
    publicAccess: true,
  },
  {
    id: 'greenhouse-geisser-1959',
    author: 'S. W. Greenhouse and S. Geisser',
    title: 'On Methods in the Analysis of Profile Data',
    year: '1959',
    edition: 'Psychometrika, 24, 95–112',
    url: 'https://doi.org/10.1007/BF02289823',
    note: 'Epsilon correction for repeated-measures tests when sphericity is violated.',
    publicAccess: false,
  },
  {
    id: 'huynh-feldt-1976',
    author: 'H. Huynh and L. S. Feldt',
    title: 'Estimation of the Box Correction for Degrees of Freedom from Sample Data in Randomized Block and Split-Plot Designs',
    year: '1976',
    edition: 'Journal of Educational Statistics, 1(1), 69–82',
    url: 'https://doi.org/10.3102/10769986001001069',
    note: 'Alternative epsilon estimator for repeated-measures degrees-of-freedom correction.',
    publicAccess: false,
  },
  {
    id: 'fitzmaurice-laird-ware-2011',
    author: 'G. M. Fitzmaurice, N. M. Laird, and J. H. Ware',
    title: 'Applied Longitudinal Analysis',
    year: '2011',
    edition: '2nd ed., Wiley Series in Probability and Statistics',
    url: 'https://doi.org/10.1002/9781119513469',
    note: 'Covariance-structured repeated-measures and longitudinal mixed models, including Wald-style inference.',
    publicAccess: false,
  },
  {
    id: 'plackett-burman-1946',
    author: 'R. L. Plackett and J. P. Burman',
    title: 'The Design of Optimum Multifactorial Experiments',
    year: '1946',
    edition: 'Biometrika, 33(4), 305–325',
    url: 'https://doi.org/10.1093/biomet/33.4.305',
    note: 'Original construction of economical orthogonal screening designs.',
    publicAccess: false,
  },
  {
    id: 'scheffe-anova-1959',
    author: 'Henry Scheffé',
    title: 'The Analysis of Variance',
    year: '1959',
    edition: 'Wiley Classics Library edition available; original monograph',
    note: 'Foundational fixed-, random-, and mixed-effects analysis-of-variance theory; use the cited chapter locator.',
    publicAccess: false,
  },
  {
    id: 'scheffe-mixtures-1958',
    author: 'Henry Scheffé',
    title: 'Experiments with Mixtures',
    year: '1958',
    edition: 'Journal of the Royal Statistical Society, Series B, 20(2), 344–360',
    note: 'Canonical polynomial models and simplex designs for mixture experiments.',
    publicAccess: false,
  },
  {
    id: 'nrc-fault-tree',
    author: 'W. E. Vesely, F. F. Goldberg, N. H. Roberts, and D. F. Haasl; U.S. Nuclear Regulatory Commission',
    title: 'Fault Tree Handbook (NUREG-0492)',
    year: '1981',
    url: 'https://www.nrc.gov/reading-rm/doc-collections/nuregs/staff/sr0492/index',
    note: 'Fault-tree construction, qualitative analysis, minimal cut sets, and quantification.',
    publicAccess: true,
  },
  {
    id: 'nrc-common-cause',
    author: 'A. Mosleh et al.; U.S. Nuclear Regulatory Commission',
    title: 'Guidelines on Modeling Common-Cause Failures in Probabilistic Risk Assessment (NUREG/CR-5485)',
    year: '1998',
    edition: 'Volume 1',
    url: 'https://www.nrc.gov/reading-rm/doc-collections/nuregs/contract/cr5485/index',
    note: 'Common-cause failure identification and parametric modeling guidance.',
    publicAccess: true,
  },
  {
    id: 'nrc-spar-h',
    author: 'D. I. Gertman et al.; U.S. Nuclear Regulatory Commission',
    title: 'The SPAR-H Human Reliability Analysis Method (NUREG/CR-6883)',
    year: '2005',
    url: 'https://www.nrc.gov/sites/default/files/doc_library/cdn/legacy/reading-rm/doc-collections/nuregs/contract/cr6883/cr6883.pdf',
    note: 'Nominal HEPs, eight PSFs, dependency, worksheets, uncertainty, and method limitations.',
    publicAccess: true,
  },
  {
    id: 'nrc-atheana',
    author: 'U.S. Nuclear Regulatory Commission',
    title: 'Technical Basis and Implementation Guidelines for A Technique for Human Event Analysis (ATHEANA) (NUREG-1624)',
    year: '2000',
    edition: 'Revision 1',
    url: 'https://www.nrc.gov/reading-rm/doc-collections/nuregs/staff/sr1624/index',
    note: 'Complete ATHEANA event definition, unsafe-action and error-forcing-context searches, review, dependence, and quantification workflow.',
    publicAccess: true,
  },
  {
    id: 'nrc-therp',
    author: 'A. D. Swain and H. E. Guttmann; U.S. Nuclear Regulatory Commission',
    title: 'Handbook of Human-Reliability Analysis with Emphasis on Nuclear Power Plant Applications (NUREG/CR-1278)',
    year: '1983',
    edition: 'Final Report',
    url: 'https://www.nrc.gov/reading-rm/doc-collections/nuregs/contract/cr1278/index',
    note: 'THERP task decomposition, nominal HEP tables, performance-shaping factors, and dependence treatment.',
    publicAccess: true,
  },
  {
    id: 'williams-1986-heart',
    author: 'J. C. Williams',
    title: 'HEART—A Proposed Method for Assessing and Reducing Human Error',
    year: '1986',
    edition: 'Proceedings of the 9th Advances in Reliability Technology Symposium',
    note: 'Original HEART generic task and error-producing-condition method description.',
    publicAccess: false,
  },
  {
    id: 'hollnagel-1998-cream',
    author: 'Erik Hollnagel',
    title: 'Cognitive Reliability and Error Analysis Method (CREAM)',
    year: '1998',
    edition: '1st ed., Elsevier',
    url: 'https://doi.org/10.1016/B978-0-08-042848-2.X5000-3',
    note: 'Basic control modes, common performance conditions, cognitive functions, and extended analysis.',
    publicAccess: false,
  },
  {
    id: 'embrey-1984-slim',
    author: 'D. E. Embrey et al.; U.S. Nuclear Regulatory Commission',
    title: 'SLIM-MAUD: An Approach to Assessing Human Error Probabilities Using Structured Expert Judgment (NUREG/CR-3518)',
    year: '1984',
    note: 'Success Likelihood Index Method with multi-attribute utility decomposition and calibration.',
    publicAccess: true,
  },
  {
    id: 'mil-hdbk-189c',
    author: 'U.S. Department of Defense',
    title: 'Reliability Growth Management',
    year: '2011',
    edition: 'MIL-HDBK-189C',
    note: 'Public U.S. DoD handbook. Cite the applicable method, appendix, table, or paragraph locator shown in Help.',
    publicAccess: true,
  },
  {
    id: 'mil-hdbk-217f',
    author: 'U.S. Department of Defense',
    title: 'Reliability Prediction of Electronic Equipment',
    year: '1991–1995',
    edition: 'MIL-HDBK-217F, Notice 2',
    note: 'Public U.S. DoD handbook. Perdura citations identify the relevant section/table; no local reference-file URL is exposed.',
    publicAccess: true,
  },
  {
    id: 'vita-51-1',
    author: 'VITA Standards Organization',
    title: 'Reliability Prediction MIL-HDBK-217 Subsidiary Specification',
    year: '2018',
    edition: 'ANSI/VITA 51.1-2013 (R2018)',
    note: 'Controlled standard; consult a licensed copy and use Perdura’s clause/table locator. The application does not redistribute or link to a local copy.',
    publicAccess: false,
  },
  {
    id: 'telcordia-sr332',
    author: 'Telcordia Technologies / Ericsson',
    title: 'Reliability Prediction Procedure for Electronic Equipment',
    year: '2016',
    edition: 'Telcordia SR-332, Issue 4',
    url: 'https://telecom-info.njdepot.ericsson.net/',
    note: 'Licensed standard. Perdura implements a screening subset and does not reproduce the full Methods I–III workflow, tables, field-data updating, or official examples.',
    publicAccess: false,
  },
  {
    id: '217plus-2015',
    author: 'Quanterion Solutions Incorporated',
    title: 'Handbook of 217Plus Reliability Prediction Models',
    year: '2017',
    edition: 'HDBK-217Plus:2015, Notice 1',
    url: 'https://www.quanterion.com/product/publications/hdbk-217plus-2015-notice-1',
    note: 'Commercial handbook. Perdura’s screening model does not reproduce its licensed database, full failure-mode model, process assessment, or official examples.',
    publicAccess: false,
  },
  {
    id: 'fides-guide',
    author: 'IMdR FIDES Working Group',
    title: 'FIDES Guide 2022 Edition A',
    year: '2023',
    edition: 'English release, July 2023',
    url: 'https://www.fides-reliability.org/en/node/5',
    note: 'Official methodology portal and download index for the 2022 component, mission-profile, and process-factor guide used to identify Perdura’s implementation target.',
    publicAccess: true,
  },
  {
    id: 'nswc-98-le1',
    author: 'Naval Surface Warfare Center, Carderock Division',
    title: 'Handbook of Reliability Prediction Procedures for Mechanical Equipment',
    year: '1998',
    edition: 'NSWC-98/LE1',
    note: 'Government mechanical-equipment handbook. Perdura implements selected component models with identified simplified modifiers, not the complete handbook.',
    publicAccess: true,
  },
  {
    id: 'eprd-2014',
    author: 'Quanterion Solutions Incorporated / Reliability Information Analysis Center',
    title: 'Electronic Parts Reliability Data',
    year: '2014',
    edition: 'EPRD-2014',
    url: 'https://www.quanterion.com/wp-content/uploads/2015/09/Front-Material-for-PDF-Viewer-EPRD.pdf',
    note: 'The linked front material is public; the record-level database is commercial. Perdura uses representative aggregate screening rates rather than licensed table extracts.',
    publicAccess: true,
  },
  {
    id: 'nprd-2023',
    author: 'Quanterion Solutions Incorporated',
    title: 'Nonelectronic Parts Reliability Data',
    year: '2023',
    edition: 'NPRD-2023',
    url: 'https://www.quanterion.com/wp-content/uploads/2023/03/NPRD-2023-Parts-Descriptions-1.pdf',
    note: 'The linked part descriptions are public; the record-level database is commercial. Perdura uses representative aggregate screening rates rather than licensed table extracts.',
    publicAccess: true,
  },
  {
    id: 'nasa-fides-pof',
    author: 'M. Pecht, D. Das, and A. Gaonkar; NASA Electronic Parts and Packaging Program',
    title: 'Evaluation and Comparison of FIDES and PoF-Based EEE Part Reliability Assessment',
    year: '2020',
    url: 'https://nepp.nasa.gov/docs/papers/2020-NASA-FIDES-CALCE-Report-Univ-MD-Pecht-Das-Gaonkar.pdf',
    note: 'Critical NASA/CALCE assessment of FIDES Guide 2009 and handbook prediction versus physics-of-failure approaches; it is context, not documentation of the 2022 edition.',
    publicAccess: true,
  },
  {
    id: 'nasa-forman',
    author: 'R. G. Forman, V. E. Kearney, and R. M. Engle; NASA',
    title: 'Numerical Analysis of Crack Propagation in Cyclic-Loaded Structures',
    year: '1967',
    edition: 'Journal of Basic Engineering, 89(3), 459–463',
    url: 'https://doi.org/10.1115/1.3609637',
    note: 'Forman fatigue-crack-growth relation including the stress-ratio/fracture-toughness denominator.',
    publicAccess: false,
  },
  {
    id: 'norris-landzberg-1969',
    author: 'K. C. Norris and A. H. Landzberg',
    title: 'Reliability of Controlled Collapse Interconnections',
    year: '1969',
    edition: 'IBM Journal of Research and Development, 13(3), 266–271',
    url: 'https://doi.org/10.1147/rd.133.0266',
    note: 'Original thermal-cycling acceleration treatment underlying the Norris–Landzberg solder-interconnect model.',
    publicAccess: false,
  },
  {
    id: 'peck-1986',
    author: 'D. S. Peck',
    title: 'Comprehensive Model for Humidity Testing Correlation',
    year: '1986',
    edition: '24th Annual Reliability Physics Symposium, 44–50',
    url: 'https://doi.org/10.1109/IRPS.1986.362110',
    note: 'Temperature–humidity acceleration model commonly known as the Peck relation.',
    publicAccess: false,
  },
  {
    id: 'black-1969',
    author: 'J. R. Black',
    title: 'Electromigration—A Brief Survey and Some Recent Results',
    year: '1969',
    edition: 'IEEE Transactions on Electron Devices, 16(4), 338–347',
    url: 'https://doi.org/10.1109/T-ED.1969.16754',
    note: 'Current-density and temperature dependence used in Black-type electromigration life models.',
    publicAccess: false,
  },
  {
    id: 'nasa-nasalife',
    author: 'J. Z. Gyekenyesi, P. L. N. Murthy, and S. K. Mital; NASA Glenn Research Center',
    title: 'NASALife—Component Fatigue and Creep-Fatigue Life Prediction Methodology',
    year: '2014',
    edition: 'NASA/TM-2005-213886/REV2',
    url: 'https://ntrs.nasa.gov/search.jsp?R=20140010774',
    note: 'Public NASA life-prediction methodology covering fatigue, creep, damage accumulation, and supporting constitutive relations. Topic citations identify the applicable section or equation.',
    publicAccess: true,
  },
  {
    id: 'nasa-miner',
    author: 'S. S. Manson; NASA Lewis Research Center',
    title: 'Interpretive Report on Cumulative Fatigue Damage in the Low Cycle Range: Optimization of Palmgren-Miner Determinations of Cumulative Fatigue Damage',
    year: '1964',
    edition: 'NASA-RP-310',
    url: 'https://ntrs.nasa.gov/citations/19640020692',
    note: 'Public NASA treatment of Palmgren–Miner cumulative damage, including interpretation and limitations.',
    publicAccess: true,
  },
  {
    id: 'sklearn-cross-validation',
    author: 'scikit-learn developers',
    title: 'Cross-validation: Evaluating Estimator Performance',
    url: 'https://scikit-learn.org/stable/modules/cross_validation.html',
    note: 'Data splitting, cross-validation strategies, and leakage-aware model evaluation.',
    publicAccess: true,
  },
  {
    id: 'sklearn-calibration',
    author: 'scikit-learn developers',
    title: 'Probability Calibration',
    url: 'https://scikit-learn.org/stable/modules/calibration.html',
    note: 'Calibration curves, sigmoid/isotonic calibration, and properly separated calibration data.',
    publicAccess: true,
  },
  {
    id: 'sklearn-lasso',
    author: 'scikit-learn developers',
    title: 'Lasso and Elastic Net',
    url: 'https://scikit-learn.org/stable/modules/linear_model.html#lasso',
    note: 'L1 and mixed L1/L2 regularized linear models and their optimization behavior.',
    publicAccess: true,
  },
  {
    id: 'scikit-learn-user-guide',
    author: 'scikit-learn developers',
    title: 'scikit-learn User Guide',
    url: 'https://scikit-learn.org/stable/user_guide.html',
    note: 'Primary implementation reference for supported preprocessing, estimators, metrics, inspection, and model-selection workflows.',
    publicAccess: true,
  },
]
