import type { GlossaryEntry } from './types'

export const HELP_GLOSSARY: GlossaryEntry[] = [
  {
    id: 'acceleration-factor', term: 'Acceleration factor', aliases: ['AF'],
    short: 'Ratio of characteristic life or reaction rate between use and accelerated stress conditions.',
    detail: 'Its direction must be stated: Perdura topics identify whether AF multiplies life, rate, or time transformation. Extrapolation is credible only while the same failure mechanism and acceleration relationship remain active.',
    relatedTopics: ['alt.overview', 'pof.overview'], citations: [{ id: 'nist-alt-mle' }],
  },
  {
    id: 'activation-energy', term: 'Activation energy', aliases: ['Ea', 'Eₐ'],
    short: 'Energy barrier used in Arrhenius temperature-acceleration models.',
    detail: 'Use electron-volts with Boltzmann’s constant in eV/K, or joules with J/K. Unit mismatches silently create extreme acceleration errors.',
    relatedTopics: ['pof.arrhenius', 'alt.acceleration-arrhenius'],
  },
  {
    id: 'aicc', term: 'AICc', aliases: ['corrected Akaike information criterion'],
    short: 'Akaike information criterion with an added finite-sample penalty.',
    detail: 'Lower values indicate better estimated predictive information tradeoff among models fitted to the same observations and likelihood. AICc is not an absolute goodness-of-fit test.',
    relatedTopics: ['lifeData.fit-everything', 'dataAnalysis.validation'], citations: [{ id: 'hurvich-tsai-1989' }],
  },
  {
    id: 'anderson-darling', term: 'Anderson–Darling statistic', aliases: ['AD statistic'],
    short: 'CDF discrepancy measure that gives comparatively strong weight to distribution tails.',
    detail: 'Values are comparable only under the same fitting and observation conventions; estimated parameters and censoring affect calibration.',
    relatedTopics: ['lifeData.fit-everything'],
  },
  {
    id: 'availability', term: 'Availability', aliases: ['steady-state availability'],
    short: 'Long-run probability or fraction of time that an item is able to perform as required.',
    detail: 'Inherent, achieved, operational, steady-state Markov, and finite-horizon availability have different inclusions and denominators; always report the definition.',
    relatedTopics: ['maintenance.availability', 'systemModeling.markov'],
  },
  {
    id: 'operational-availability', term: 'Operational availability', aliases: ['Ao', 'Aₒ'],
    short: 'Availability including active repair plus administrative and logistics downtime.',
    detail: 'Perdura’s closed-form Maintenance calculation uses mean uptime divided by mean uptime plus mean downtime.',
    relatedTopics: ['maintenance.availability', 'maintenance.availability-sensitivity'],
  },
  {
    id: 'bootstrap', term: 'Bootstrap', aliases: ['bootstrap resampling'],
    short: 'Approximate repeated-sampling uncertainty by resampling the observed units or another justified sampling unit.',
    detail: 'Ordinary row resampling is inappropriate when observations are clustered, grouped, serially dependent, or censored in a way that requires a structured bootstrap.',
    relatedTopics: ['lifeData.calibrated-intervals', 'dataAnalysis.validation'],
  },
  {
    id: 'calibrated-scalar-interval', term: 'Calibrated scalar interval',
    short: 'A scalar uncertainty interval whose nominal coverage has been adjusted or validated for the fitted quantity and regime.',
    detail: 'It describes uncertainty for a single reported parameter or metric, not a simultaneous band for an entire reliability curve. Read the method and calibration status shown with the result.',
    relatedTopics: ['lifeData.calibrated-intervals'],
  },
  {
    id: 'calibration', term: 'Probability calibration', aliases: ['classifier calibration'],
    short: 'Agreement between predicted probabilities and observed event frequencies.',
    detail: 'Calibration must be estimated and evaluated on held-out data. A model can discriminate well while assigning systematically biased probabilities.',
    relatedTopics: ['dataAnalysis.calibration'], citations: [{ id: 'sklearn-calibration' }],
  },
  {
    id: 'censoring', term: 'Censoring', aliases: ['censored observation'],
    short: 'Partial information about an event time rather than an exactly observed failure time.',
    detail: 'Right, left, and interval censoring contribute different likelihood terms. Censoring is not the same as deleting or imputing a failure time.',
    relatedTopics: ['lifeData.observation-individual', 'warranty.workflow'], citations: [{ id: 'nist-apr-censoring' }],
  },
  {
    id: 'right-censoring', term: 'Right censoring', aliases: ['suspension'],
    short: 'The unit has not experienced the modeled event by its last observed time.',
    detail: 'It contributes survival probability S(t), not a failure at t. The censoring process should be noninformative conditional on modeled information.',
    relatedTopics: ['lifeData.observation-individual', 'warranty.workflow'], citations: [{ id: 'nist-apr-censoring' }],
  },
  {
    id: 'interval-censoring', term: 'Interval censoring', aliases: ['interval-censored failure'],
    short: 'The event is known to occur in an interval (l, u] but not at an exact time.',
    detail: 'Its likelihood contribution is F(u)−F(l). Replacing the interval with its midpoint discards observation information and can bias a fit.',
    relatedTopics: ['lifeData.observation-interval', 'warranty.workflow'], citations: [{ id: 'turnbull-1976' }],
  },
  {
    id: 'confidence-interval', term: 'Confidence interval', aliases: ['CI'],
    short: 'An interval produced by a procedure designed to cover a fixed population quantity at a stated long-run rate.',
    detail: 'It is not the probability that the already-fixed true value lies in this particular interval. Check whether the method is Wald, profile, exact, bootstrap, or another construction.',
    relatedTopics: ['hypothesis.overview', 'lifeData.calibrated-intervals'],
  },
  {
    id: 'prediction-interval', term: 'Prediction interval',
    short: 'An interval for a future observation or aggregate outcome, including outcome variation under the stated method.',
    detail: 'A parameter confidence interval is generally narrower and answers a different question. Perdura labels parameter-only warranty intervals explicitly.',
    relatedTopics: ['dataAnalysis.prediction', 'warranty.workflow'],
  },
  {
    id: 'common-cause-failure', term: 'Common-cause failure', aliases: ['CCF'],
    short: 'Dependent failure of multiple components from a shared cause or coupling mechanism.',
    detail: 'Independent-event multiplication can materially understate system risk when common-cause coupling is credible.',
    relatedTopics: ['systemModeling.fault-tree'], citations: [{ id: 'nrc-common-cause' }],
  },
  {
    id: 'control-mode', term: 'CREAM control mode', aliases: ['control mode'],
    short: 'Contextual CREAM classification—strategic, tactical, opportunistic, or scrambled—derived from common performance conditions.',
    detail: 'Basic CREAM maps the mode to a broad HEP interval; its displayed midpoint should not be treated as a high-precision task estimate.',
    relatedTopics: ['hra.cream'], citations: [{ id: 'hollnagel-1998-cream' }],
  },
  {
    id: 'common-performance-condition', term: 'Common performance condition', aliases: ['CPC'],
    short: 'CREAM contextual factor describing how working conditions improve, reduce, or do not significantly affect performance reliability.',
    detail: 'Examples include organizational adequacy, procedures, available time, training, and crew collaboration.',
    relatedTopics: ['hra.cream', 'hra.cream-extended'], citations: [{ id: 'hollnagel-1998-cream' }],
  },
  {
    id: 'cross-validation', term: 'Cross-validation', aliases: ['CV'],
    short: 'Repeatedly train on one subset and evaluate on held-out observations to estimate out-of-sample performance.',
    detail: 'Preprocessing and tuning must occur inside the corresponding training data. Grouped and time-ordered data require structure-aware splits.',
    relatedTopics: ['dataAnalysis.validation'], citations: [{ id: 'sklearn-cross-validation' }],
  },
  {
    id: 'cumulative-hazard', term: 'Cumulative hazard', aliases: ['H(t)'],
    short: 'Integrated hazard through time t; for continuous life models, H(t)=−ln S(t).',
    detail: 'For a minimal-repair Weibull process, the expected event count over an interval can equal the cumulative hazard.',
    relatedTopics: ['maintenance.replacement', 'growth.crow-amsaa'],
  },
  {
    id: 'damage-accumulation', term: 'Cumulative damage', aliases: ['damage accumulation'],
    short: 'A rule that combines exposure from multiple loads or environments into a total damage measure.',
    detail: 'Linear Miner summation is convenient but ignores load-order and interaction effects; mechanism-specific nonlinear models may be required.',
    relatedTopics: ['pof.damage'], citations: [{ id: 'nasa-miner' }],
  },
  {
    id: 'duty-cycle', term: 'Duty cycle',
    short: 'Fraction of calendar exposure during which an item operates in the stated active condition.',
    detail: 'In Maintenance calculations this scales accumulated active exposure. Failure Rate Prediction instead labels and models operating fraction and nonoperating exposure explicitly.',
    relatedTopics: ['maintenance.spares'],
  },
  {
    id: 'operating-fraction', term: 'Operating fraction',
    short: 'Fraction of calendar time represented by the active operating state in a service-life prediction.',
    detail: 'Perdura combines the MIL-HDBK-217F operating rate with a separate RADC-TR-85-91 nonoperating rate. Nested System Block operating fractions multiply.',
    relatedTopics: ['prediction.radc-tr-85-91', 'prediction.system-blocks'],
    citations: [{ id: 'radc-tr-85-91' }],
  },
  {
    id: 'service-life-rate', term: 'Service-life failure rate', aliases: ['calendar-time failure rate'],
    short: 'Operating-fraction-weighted rate expressed per unit of total calendar exposure.',
    detail: 'The source operating and nonoperating rates retain their state-specific exposure bases; their weighted service-life result is suitable for the constant-rate calendar-time reliability calculation.',
    relatedTopics: ['prediction.radc-tr-85-91', 'prediction.mission-profile'],
    citations: [{ id: 'radc-tr-85-91' }],
  },
  {
    id: 'effect-size', term: 'Effect size',
    short: 'Magnitude of a difference, association, or standardized model effect, separate from its p-value.',
    detail: 'Interpret it in domain units when possible and accompany it with uncertainty and a practical-significance threshold.',
    relatedTopics: ['hypothesis.overview'],
  },
  {
    id: 'error-forcing-context', term: 'Error-forcing context', aliases: ['EFC'],
    short: 'Situation in which plant conditions and performance factors make an unsafe action understandable or likely.',
    detail: 'Perdura’s EFC Elicitation tab is a screening worksheet, not the complete ATHEANA identification, review, dependence, and quantification process.',
    relatedTopics: ['hra.atheana'], citations: [{ id: 'nrc-atheana' }],
  },
  {
    id: 'failure-rate', term: 'Failure rate', aliases: ['lambda', 'λ'],
    short: 'Event frequency per unit exposure under a specified population, state, and model.',
    detail: 'A handbook predicted rate, empirical ROCOF, instantaneous hazard, and constant exponential rate are related but not interchangeable.',
    relatedTopics: ['prediction.overview', 'growth.rocof'],
  },
  {
    id: 'hazard-function', term: 'Hazard function', aliases: ['hazard rate', 'h(t)'],
    short: 'Instantaneous event rate at age t conditional on survival to t.',
    detail: 'It is h(t)=f(t)/S(t) for continuous lifetime models and can vary with age even when an average failure rate is reported.',
    relatedTopics: ['lifeData.parametric'],
  },
  {
    id: 'human-error-probability', term: 'Human error probability', aliases: ['HEP'],
    short: 'Probability of a precisely defined human failure event under stated conditions.',
    detail: 'Task boundary, opportunity, cues, recovery, context, and dependency are part of the definition. Values from different HRA methods are not interchangeable uncertainty bounds.',
    relatedTopics: ['hra.overview', 'hra.therp', 'hra.spar-h'],
  },
  {
    id: 'grouped-likelihood', term: 'Grouped likelihood', aliases: ['weighted grouped likelihood'],
    short: 'Likelihood that preserves aggregate counts as weights on exact, censored, or interval observations.',
    detail: 'For warranty periods, return counts multiply log interval probabilities and survivors multiply log survival probabilities; observations are not expanded or rounded.',
    relatedTopics: ['warranty.workflow', 'lifeData.observation-interval'], citations: [{ id: 'turnbull-1976' }],
  },
  {
    id: 'mean-cumulative-function', term: 'Mean cumulative function', aliases: ['MCF'],
    short: 'Expected cumulative number of recurrent events per item by time t.',
    detail: 'MCF supports repairable-system recurrent-event data and differs from a nonrepairable failure CDF.',
    relatedTopics: ['growth.mcf'], citations: [{ id: 'nelson-2003' }, { id: 'lawless-nadeau-1995' }],
  },
  {
    id: 'maintenance-free-operating-period', term: 'Maintenance-Free Operating Period', aliases: ['MFOP'],
    short: 'Planned interval over which the system is expected to meet the stated performance or reliability objective without scheduled maintenance.',
    detail: 'Perdura’s PM Interval tool uses the life-distribution quantile at a target reliability under perfect renewal.',
    relatedTopics: ['maintenance.pm-interval'],
  },
  {
    id: 'maximum-likelihood-estimation', term: 'Maximum likelihood estimation', aliases: ['MLE'],
    short: 'Choose model parameters that maximize the probability or density assigned to the observed data under the model.',
    detail: 'Censored and grouped data require the correct likelihood contributions. Large-sample optimality does not guarantee stable small-sample or boundary inference.',
    relatedTopics: ['lifeData.parametric', 'warranty.workflow', 'alt.overview'], citations: [{ id: 'nist-alt-mle' }],
  },
  {
    id: 'mean-down-time', term: 'Mean down time', aliases: ['MDT'],
    short: 'Average unavailable time per downtime cycle under the stated inclusions.',
    detail: 'In the Maintenance availability calculation, MDT is MTTR plus administrative and logistics delay.',
    relatedTopics: ['maintenance.availability'],
  },
  {
    id: 'mean-time-between-failures', term: 'Mean time between failures', aliases: ['MTBF'],
    short: 'Mean operating time between failures for a repairable item under a specified regime.',
    detail: 'MTBF is not generally a nonrepairable component’s life quantile and does not by itself imply an exponential distribution.',
    relatedTopics: ['maintenance.availability', 'prediction.overview'],
  },
  {
    id: 'mean-time-between-maintenance', term: 'Mean time between maintenance', aliases: ['MTBM'],
    short: 'Mean operating time between all maintenance events, including preventive actions when defined that way.',
    detail: 'Perdura uses MTBM as the achieved-availability uptime basis and, when supplied, the operational-availability basis.',
    relatedTopics: ['maintenance.availability'],
  },
  {
    id: 'mean-time-to-failure', term: 'Mean time to failure', aliases: ['MTTF'],
    short: 'Expected lifetime of a nonrepairable population under its fitted life distribution.',
    detail: 'MTTF can be unstable or undefined for some heavy-tailed models and should not replace reliability at a mission time.',
    relatedTopics: ['lifeData.parametric', 'maintenance.replacement'],
  },
  {
    id: 'mean-time-to-repair', term: 'Mean time to repair', aliases: ['MTTR'],
    short: 'Mean active corrective restoration time under a stated start/stop definition.',
    detail: 'Keep administrative and logistics delays separate unless the organization’s MTTR definition explicitly includes them.',
    relatedTopics: ['maintenance.availability', 'maintenance.maintainability'],
  },
  {
    id: 'minimal-cut-set', term: 'Minimal cut set', aliases: ['MCS'],
    short: 'Smallest combination of basic events sufficient to cause a fault-tree top event.',
    detail: 'Minimality is logical, not probabilistic; ranking also depends on event probabilities and dependencies.',
    relatedTopics: ['systemModeling.fault-tree'], citations: [{ id: 'nrc-fault-tree' }],
  },
  {
    id: 'nonparametric-estimate', term: 'Nonparametric estimate',
    short: 'Estimate that does not impose one finite-dimensional distribution family on the population.',
    detail: 'Kaplan–Meier, Turnbull, and MCF methods still have assumptions and can be imprecise where support is sparse.',
    relatedTopics: ['lifeData.nonparametric', 'growth.mcf'],
  },
  {
    id: 'nevada-chart', term: 'Nevada chart', aliases: ['warranty cohort chart'],
    short: 'Upper-triangular table of quantities shipped by period and returns from each lot in later periods.',
    detail: 'Each return-period cell represents an age interval for its shipment lot; surviving units are right-censored at the lot’s current age.',
    relatedTopics: ['warranty.workflow'],
  },
  {
    id: 'overfitting', term: 'Overfitting',
    short: 'Learning sample-specific noise or quirks that do not generalize to new observations.',
    detail: 'Nested tuning, appropriate cross-validation, parsimonious models, and honest held-out diagnostics reduce but do not eliminate overfitting risk.',
    relatedTopics: ['dataAnalysis.validation'], citations: [{ id: 'sklearn-cross-validation' }],
  },
  {
    id: 'performance-shaping-factor', term: 'Performance-shaping factor', aliases: ['PSF'],
    short: 'Context or condition assessed as changing the likelihood of human performance success or failure.',
    detail: 'Definitions and multipliers are method-specific. Avoid counting correlated context under several overlapping factors.',
    relatedTopics: ['hra.spar-h', 'hra.slim'], citations: [{ id: 'nrc-spar-h' }],
  },
  {
    id: 'poisson-process', term: 'Poisson process', aliases: ['HPP', 'homogeneous Poisson process'],
    short: 'Independent-event counting process with constant rate and Poisson counts over fixed exposure.',
    detail: 'It implies count variance equal to the mean and exponential interarrival times. Trend, overdispersion, or clustering contradict the homogeneous model.',
    relatedTopics: ['maintenance.spares', 'growth.rocof'],
  },
  {
    id: 'process-capability', term: 'Process capability', aliases: ['Cp', 'Cpk', 'Pp', 'Ppk'],
    short: 'Diagnostic comparison of process spread and centering with specification limits.',
    detail: 'Capability interpretation requires a stable process and a distribution/tail method appropriate to the data; specification limits are not control limits.',
    relatedTopics: ['sixSigma.capability'], citations: [{ id: 'nist-process-stability' }],
  },
  {
    id: 'profile-likelihood', term: 'Profile likelihood', aliases: ['likelihood profile'],
    short: 'Likelihood for one parameter or derived quantity after reoptimizing nuisance parameters at each fixed value.',
    detail: 'It often handles asymmetry better than a Wald interval but can still be nonregular at exact boundaries or under weak identification.',
    relatedTopics: ['lifeData.calibrated-intervals', 'growth.crow-amsaa'],
  },
  {
    id: 'p-value', term: 'p-value',
    short: 'Probability, under the null model, of a test statistic at least as incompatible with that model as the observed statistic.',
    detail: 'It is not the probability that the null hypothesis is true and does not measure practical importance.',
    relatedTopics: ['hypothesis.overview'],
  },
  {
    id: 'regularization', term: 'Regularization', aliases: ['penalization'],
    short: 'Add a complexity penalty to model fitting to stabilize estimates or shrink/select predictors.',
    detail: 'L1 can set coefficients to zero; L2 shrinks them continuously; elastic net combines both. Penalty strength must be selected within training data.',
    relatedTopics: ['dataAnalysis.lasso'], citations: [{ id: 'sklearn-lasso' }],
  },
  {
    id: 'renewal-process', term: 'Renewal process',
    short: 'Event process whose interarrival times restart independently after complete renewal.',
    detail: 'Age replacement is a renewal policy; minimal repair and imperfect virtual-age repair are not ordinary complete renewals.',
    relatedTopics: ['maintenance.replacement', 'maintenance.spares', 'maintenance.virtual-age'],
  },
  {
    id: 'repeatability', term: 'Measurement repeatability', aliases: ['equipment variation'],
    short: 'Variation when the same operator and measurement system repeatedly measure under the same conditions.',
    detail: 'Repeatability is one component of measurement-system variation and must be separated from part-to-part variation.',
    relatedTopics: ['sixSigma.msa'], citations: [{ id: 'nist-gage-rr' }],
  },
  {
    id: 'reproducibility', term: 'Measurement reproducibility', aliases: ['appraiser variation'],
    short: 'Measurement variation associated with operators or other changed measurement conditions.',
    detail: 'In a Gage R&R study, the estimable reproducibility components depend on whether the design is crossed, nested, balanced, or unbalanced.',
    relatedTopics: ['sixSigma.msa'], citations: [{ id: 'nist-gage-rr' }],
  },
  {
    id: 'reliability-function', term: 'Reliability function', aliases: ['survival function', 'R(t)', 'S(t)'],
    short: 'Probability that lifetime exceeds t: R(t)=S(t)=1−F(t).',
    detail: 'Its interpretation depends on the event definition, population, conditions, and time origin.',
    relatedTopics: ['lifeData.parametric', 'maintenance.pm-interval'],
  },
  {
    id: 'screening-design', term: 'Screening design',
    short: 'Economical experiment intended to identify a small number of important factors among many candidates.',
    detail: 'Resolution, aliasing, effect hierarchy, and interaction assumptions determine what can be learned. Screening is normally followed by confirmation or optimization.',
    relatedTopics: ['sixSigma.doe'], citations: [{ id: 'plackett-burman-1946' }],
  },
  {
    id: 'sphericity', term: 'Sphericity',
    short: 'Repeated-measures assumption that variances of all pairwise condition differences are equal.',
    detail: 'Mauchly’s test is a diagnostic; Greenhouse–Geisser or Huynh–Feldt epsilon can adjust degrees of freedom when the assumption is not tenable.',
    relatedTopics: ['hypothesis.rm_anova'], citations: [{ id: 'mauchly-1940' }, { id: 'greenhouse-geisser-1959' }, { id: 'huynh-feldt-1976' }],
  },
  {
    id: 'statistical-power', term: 'Statistical power', aliases: ['test power'],
    short: 'Probability that a specified test rejects the null when a specified alternative effect is true.',
    detail: 'Power depends on effect size, sample size, variance, significance level, design, and test assumptions. Post-hoc power from the observed effect adds little beyond the p-value.',
    relatedTopics: ['hypothesis.overview', 'sixSigma.doe'],
  },
  {
    id: 'stockout-protection', term: 'Stockout protection', aliases: ['no-stockout probability'],
    short: 'Model-based probability that the chosen spare stock is sufficient over the specified horizon.',
    detail: 'Analytic period-demand protection and simulated maximum-outstanding-pipeline protection answer different inventory questions.',
    relatedTopics: ['maintenance.spares'],
  },
  {
    id: 'success-likelihood-index', term: 'Success Likelihood Index', aliases: ['SLI'],
    short: 'Weighted average of expert ratings used by SLIM-MAUD before calibration to log10(HEP).',
    detail: 'SLI is relative and dimensionless; credible HEP output depends on the anchor-task calibration.',
    relatedTopics: ['hra.slim'], citations: [{ id: 'embrey-1984-slim' }],
  },
  {
    id: 'virtual-age', term: 'Virtual age', aliases: ['effective age'],
    short: 'Modeled age that represents how much deterioration remains after imperfect maintenance.',
    detail: 'In the implemented Kijima Type-II model, post-maintenance virtual age is q times the pre-maintenance virtual age; q=0 is perfect renewal and q=1 is minimal repair.',
    relatedTopics: ['maintenance.virtual-age'], citations: [{ id: 'kijima-1989' }],
  },
  {
    id: 'weibull-shape', term: 'Weibull shape parameter', aliases: ['beta', 'β'],
    short: 'Parameter controlling Weibull hazard trend: decreasing below 1, constant at 1, increasing above 1.',
    detail: 'It is dimensionless. A fitted β does not by itself identify a physical failure mechanism.',
    relatedTopics: ['lifeData.weibull-2p', 'warranty.weibull-2p', 'maintenance.replacement'],
  },
  {
    id: 'weibull-scale', term: 'Weibull scale parameter', aliases: ['eta', 'η', 'characteristic life'],
    short: 'Positive time at which the two-parameter Weibull CDF reaches 1−e⁻¹ ≈ 63.2%.',
    detail: 'It is not the Weibull mean except in the exponential special case β=1.',
    relatedTopics: ['lifeData.weibull-2p', 'warranty.weibull-2p'],
  },
]
