import { useState } from 'react'
import Plot from '../shared/ExportablePlot'
import { ToolLayout, Card, Field, Select, detail, fmtNum, PLOT_CFG, plotBase } from '../ALT/toolkit'
import { computeSpares } from '../../api/client'
import { useModuleState } from '../../store/project'
import { RamState, SparesState, INITIAL, pf } from './ram'

/** Analytic and simulated spare-parts provisioning. */
export default function Spares() {
  const [s, setS] = useModuleState<RamState>('ram', INITIAL)
  const sp = s.spares
  const patch = (p: Partial<SparesState>) => setS(prev => ({ ...prev, spares: { ...prev.spares, ...p } }))
  const [err, setErr] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  const run = async () => {
    setErr(null); setLoading(true)
    try {
      const r = await computeSpares({
        quantity: parseInt(sp.quantity, 10) || 1,
        op_hours: pf(sp.opHours) ?? 0,
        duty_cycle: pf(sp.dutyCycle) ?? 1,
        mtbf: sp.basis === 'mtbf' ? pf(sp.mtbf) : null,
        failure_rate: sp.basis === 'rate' ? pf(sp.rate) : null,
        confidence: pf(sp.confidence) ?? 0.95,
        model: sp.model ?? 'poisson',
        dispersion: pf(sp.dispersion) ?? 10,
        weibull_alpha: sp.model === 'renewal_pipeline' && sp.renewalBasis === 'weibull' ? pf(sp.weibullAlpha) : null,
        weibull_beta: sp.model === 'renewal_pipeline' && sp.renewalBasis === 'weibull' ? pf(sp.weibullBeta) : null,
        replenishment_lead_time_mean: pf(sp.leadMean) ?? 0,
        replenishment_lead_time_std: pf(sp.leadStd) ?? 0,
        common_shock_rate: pf(sp.shockRate) ?? 0,
        common_shock_size: parseInt(sp.shockSize) || 1,
        n_simulations: parseInt(sp.simulations) || 5000,
        seed: sp.seed?.trim() ? parseInt(sp.seed) : null,
      })
      patch({ result: r })
    } catch (e) { setErr(detail(e, 'Analysis failed')) } finally { setLoading(false) }
  }

  const r = sp.result

  const controls = (
    <>
      <Field label="Installed quantity" tip="Number of units in service." value={sp.quantity} onChange={v => patch({ quantity: v })} />
      <Field label="Operating hours" tip="Operating hours over the provisioning period." value={sp.opHours} onChange={v => patch({ opHours: v })} />
      <Field label="Duty cycle" tip="Fraction of operating hours the unit actually runs (0-1)." value={sp.dutyCycle} onChange={v => patch({ dutyCycle: v })} />
      <Select label="Demand model" value={sp.model ?? 'poisson'} onChange={v => patch({ model: v as SparesState['model'] })}
        options={[
          { value: 'poisson', label: 'Poisson (constant-rate analytic)' },
          { value: 'negative_binomial', label: 'Negative binomial (overdispersed)' },
          { value: 'renewal_pipeline', label: 'Renewal + replenishment simulation' },
        ]} />
      <Select label="Demand basis" value={sp.basis} onChange={v => patch({ basis: v as SparesState['basis'] })}
        options={[
          { value: 'mtbf', label: 'MTBF' },
          { value: 'rate', label: 'Failure rate' },
        ]} />
      {sp.basis === 'mtbf'
        ? <Field label="MTBF (per unit)" tip="Mean time between failures of one unit." value={sp.mtbf} onChange={v => patch({ mtbf: v })} />
        : <Field label="Failure rate (per hour)" tip="Failures per hour of one unit." value={sp.rate} onChange={v => patch({ rate: v })} />}
      {sp.model === 'negative_binomial' && (
        <Field label="Dispersion (size)" tip="Smaller values add more demand variance: Var = mean + mean²/size." value={sp.dispersion} onChange={v => patch({ dispersion: v })} />
      )}
      {sp.model === 'renewal_pipeline' && <>
        <Select label="Ordinary failure process" value={sp.renewalBasis ?? 'exponential'} onChange={v => patch({ renewalBasis: v as SparesState['renewalBasis'] })}
          options={[{ value: 'exponential', label: 'Exponential renewal' }, { value: 'weibull', label: 'Weibull renewal' }]} />
        {sp.renewalBasis === 'weibull' && <>
          <Field label="Weibull α" tip="Renewal interarrival scale in operating hours." value={sp.weibullAlpha} onChange={v => patch({ weibullAlpha: v })} />
          <Field label="Weibull β" tip="Renewal interarrival shape." value={sp.weibullBeta} onChange={v => patch({ weibullBeta: v })} />
        </>}
        <Field label="Replenishment lead mean" tip="Mean time until a consumed spare returns to serviceable inventory." value={sp.leadMean} onChange={v => patch({ leadMean: v })} />
        <Field label="Replenishment lead SD" tip="Standard deviation of the lognormal replenishment lead time." value={sp.leadStd} onChange={v => patch({ leadStd: v })} />
        <Field label="Common-shock rate" tip="Compound-Poisson shock arrivals per calendar hour; zero disables shocks." value={sp.shockRate} onChange={v => patch({ shockRate: v })} />
        <Field label="Demand per shock" tip="Simultaneous spare demands generated by each common shock." value={sp.shockSize} onChange={v => patch({ shockSize: v })} />
        <Field label="Simulation replicates" tip="Finite-horizon inventory simulations (200–50,000)." value={sp.simulations} onChange={v => patch({ simulations: v })} />
        <Field label="Random seed" tip="Blank for a non-deterministic run." value={sp.seed ?? ''} onChange={v => patch({ seed: v })} />
      </>}
      <Field label="Target confidence" tip="Desired probability of no stockout over the period (e.g. 0.95)." value={sp.confidence} onChange={v => patch({ confidence: v })} />
    </>
  )

  const results = r && (
    <div className="space-y-5">
      <div className="grid grid-cols-3 gap-3">
        <Card label={r.required_spares_interval
          ? `Required spares [${r.required_spares_interval.lower}, ${r.required_spares_interval.upper}]`
          : 'Required spares'} value={String(r.required_spares)} accent />
        <Card label="Expected demand" value={fmtNum(r.expected_demand)} />
        <Card label="Achieved protection" value={`${(r.achieved_protection * 100).toFixed(2)}%`} />
      </div>
      <div className="rounded border border-gray-200 bg-gray-50 p-2 text-[11px] text-gray-600">
        <span className="font-semibold">{r.model.replace(/_/g, ' ')}</span>
        {' · '}Variance {fmtNum(r.demand_variance)}
        {r.mean_peak_outstanding != null && <> · Mean peak outstanding {fmtNum(r.mean_peak_outstanding)}</>}
        <p className="mt-1 text-[10px]">{r.assumptions.join(' ')}</p>
      </div>
      <div>
        <p className="text-xs font-semibold text-gray-600 mb-1">P(no stockout) vs spares stocked</p>
        <Plot
          data={[
            ...(r.curve.protection_upper && r.curve.protection_lower ? [
              { x: r.curve.stock_level, y: r.curve.protection_upper, mode: 'lines', line: { width: 0 }, showlegend: false } as Plotly.Data,
              { x: r.curve.stock_level, y: r.curve.protection_lower, mode: 'lines', name: '95% simulation band', fill: 'tonexty', fillcolor: 'rgba(16,185,129,0.14)', line: { width: 0 } } as Plotly.Data,
            ] : []),
            { x: r.curve.stock_level, y: r.curve.protection, type: 'bar', marker: { color: '#10b981' }, name: 'P(no stockout)' },
            { x: [r.required_spares, r.required_spares], y: [0, 1], mode: 'lines', line: { color: '#ef4444', width: 2, dash: 'dot' }, name: `required = ${r.required_spares}` },
          ] as Plotly.Data[]}
          layout={{ ...plotBase, height: 320, xaxis: { title: { text: 'Spares stocked' } }, yaxis: { title: { text: 'P(no stockout)' }, range: [0, 1] } } as Plotly.Layout}
          config={PLOT_CFG} style={{ width: '100%' }} useResizeHandler />
      </div>
    </div>
  )

  return <ToolLayout
    intro="Spare-parts provisioning with three explicit scopes: constant-rate Poisson demand, overdispersed negative-binomial demand, or finite-horizon renewal/pipeline simulation with stochastic replenishment and optional compound common shocks."
    controls={controls} err={err} loading={loading} onRun={run} runLabel="Compute" results={results} />
}
